<?php
return [
    'methods' => [
        'VC' => 'Visa / MasterCard / JCB',
        'BC' => 'BCA Virtual Account',
        'M2' => 'Mandiri Virtual Account',
        'VA' => 'Maybank Virtual Account',
        'I1' => 'BNI Virtual Account',
        'B1' => 'CIMB Niaga Virtual Account',
        'BT' => 'Permata Bank Virtual Account',
        'A1' => 'ATM Bersama',
        'AG' => 'Bank Artha Graha',
        'NC' => 'Bank Neo Commerce/BNC',
        'BR' => 'BRIVA',
        'S1' => 'Bank Sahabat Sampoerna',
        'DM' => 'Danamon Virtual Account',
        'BV' => 'BSI Virtual Account',
        'OV' => 'OVO (Support Void)',
        'SA' => 'ShopeePay Apps (Support Void)',
        'LF' => 'LinkAja Apps (Fixed Fee)',
        'LA' => 'LinkAja Apps (Percentage Fee)',
        'DA' => 'DANA',
        'SL' => 'ShopeePay Account Link',
        'OL' => 'OVO Account Link',
        'SP' => 'ShopeePay QRIS',
        'NQ' => "Nobu QRIS",
        "GQ" => "Gudang Voucher QRIS",
        "SQ" => "Nusapay QRIS",
        "DN" => "Indodana Paylater (Credit)",
        "AT" => "ATOME (Credit)",
        "JP" => "Jenius Pay (E-Banking)",
        "FT" => "Pegadaian/ALFA/Pos (Retail)",
        "IR" => "Indomaret (Retail)",
    ],
];
